use_frameworks!

platform :ios, '9.0'

target 'NEPlayerView_Example' do
  pod 'NEPlayerView', :path => '../'
  pod 'Masonry'

  target 'NEPlayerView_Tests' do
    inherit! :search_paths

    
  end
end
